spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/giftcarddb
    username: postgres
    password: jasson
  sql:
    init:
      mode: always
    jpa:
      hibernate:
        ddl-auto: update
